import type { Category, Difficulty, InterviewQuestion } from "../types";
import { LAST_VERIFIED } from "./sources";

interface QuestionSeed {
  category: Category;
  difficulty: Difficulty;
  question: string;
  thesis: string;
  criteria: string[];
  counter: string;
  followUps: [string, string, ...string[]];
  evidence: string;
  sourceIds?: string[];
}

const seeds: QuestionSeed[] = [
  {
    category: "CFO 관점",
    difficulty: "CFO 압박",
    question: "김희철 CFO가 현재 가장 중요하게 보는 과제는 무엇이라고 생각합니까?",
    thesis: "재무관리·CV센터를 거친 내부 관리형 기반 위에서 AI·글로벌 성장 투자의 속도를 유지하되, 현금과 하방 위험을 숫자·기준·프로세스로 통제하는 일이라고 봅니다.",
    criteria: ["세후 ROIC·회수기간", "현금세금·신용등급 하방", "데이터 오너·검토 통제"],
    counter: "공개된 경력과 회사가 부여한 역할에서 추론한 답이며 개인의 성향이나 내부 우선순위를 단정하지 않겠습니다.",
    followUps: ["그 과제에서 세무팀이 가장 먼저 만들 관리 기준은?", "AI 투자와 주주환원이 충돌하면 무엇을 택합니까?", "어떤 지표를 월별로 보고하시겠습니까?"],
    evidence: "세무 의사결정을 금액·판단기준·프로세스와 이사회 선택지로 바꾼 경험",
    sourceIds: ["naver-cfo-profile", "naver-cfo-board", "naver-q1-2026", "naver-ai-factory"],
  },
  {
    category: "AI 투자",
    difficulty: "임원",
    question: "세무팀이 AI·GPU 투자에 어떤 가치를 줄 수 있습니까?",
    thesis: "공제액을 찾는 지원부서가 아니라 입지·계약·소유구조별 세후 현금흐름을 비교해 투자안의 순위를 바꾸는 파트너가 돼야 합니다.",
    criteria: ["세후 NPV·IRR", "공제 회수기간", "Pillar 2 상쇄 후 순효과"],
    counter: "세액공제가 커도 낮은 활용률이나 운영비를 보완하지 못하면 좋은 투자가 아닙니다.",
    followUps: ["투자세액공제가 Pillar 2에서 무력화되면?", "GPU 리스와 매입을 어떻게 비교합니까?", "해외 데이터센터라면 추가 검토는?"],
    evidence: "투자세액공제와 잠재환급을 사업부 투자안에 연결한 경험",
    sourceIds: ["naver-ai-cluster", "naver-ai-factory", "oecd-pillar2"],
  },
  {
    category: "두나무 거래",
    difficulty: "임원",
    question: "두나무 거래를 현금흐름 관점에서 평가해 보십시오.",
    thesis: "초기 현금대가는 제한적이지만 주식매수청구권, 거래·통합비용, 규제비용, 세금과 운전자본까지 포함한 세후 FCF로 봐야 합니다.",
    criteria: ["매수청구권 스트레스", "통합 CAPEX", "세후 시너지 회수기간"],
    counter: "주식대가는 현금 절약이지만 경제적 비용과 기존 주주 희석을 없애지는 않습니다.",
    followUps: ["현금 유출의 상한은 어떻게 잡습니까?", "시너지가 2년 늦어지면?", "거래량 급감 시 유동성 계획은?"],
    evidence: "M&A·지분거래에서 세금과 현금일정을 모델링한 경험",
    sourceIds: ["krx-deal-latest", "krx-deal-original"],
  },
  {
    category: "두나무 거래",
    difficulty: "CFO 압박",
    question: "현금이 나가지 않는 주식교환이면 좋은 거래 아닙니까?",
    thesis: "아닙니다. 현금대가를 줄였다는 장점과 희석·통합비용·실행위험을 구분하고, 거래 후 주당가치가 증가하는지로 판단해야 합니다.",
    criteria: ["희석 반영 EPS·FCF", "세후 시너지", "ROIC·중단 기준"],
    counter: "현금 보존은 신용도와 후속 투자 여력 측면에서 분명한 옵션 가치가 있습니다.",
    followUps: ["희석을 현금가치로 어떻게 환산합니까?", "언제 거래 철회를 권고합니까?", "시너지 없이도 성립할 가격입니까?"],
    evidence: "거래 구조의 법적 형식과 경제적 비용을 분리한 경험",
    sourceIds: ["krx-deal-latest"],
  },
  {
    category: "두나무 거래",
    difficulty: "CFO 압박",
    question: "두나무 주주에게 너무 많은 지분을 준 것 아닙니까?",
    thesis: "교환비율만 보고 단정할 수 없으며 양사 정상화 가치, 성장·위험 가정, 지배권, 세후 시너지를 주당가치 민감도로 검증해야 합니다.",
    criteria: ["기업가치 1:3.064569", "교환비율 2.5422618", "희석 반영 주당가치"],
    counter: "높은 비율은 두나무의 현금창출력과 성장 옵션을 반영할 수 있지만 규제·거래량 변동 할인도 필요합니다.",
    followUps: ["어떤 밸류에이션 가정을 가장 먼저 의심합니까?", "20% 거래량 하락이면?", "기존 NAVER 주주 귀속가치는 어떻게 봅니까?"],
    evidence: "가치평가 가정을 세무·현금 리스크로 검증한 경험",
    sourceIds: ["krx-deal-original"],
  },
  {
    category: "회계",
    difficulty: "임원",
    question: "거래 후 NAVER가 네이버파이낸셜을 계속 연결할 수 있는 이유는 무엇입니까?",
    thesis: "보유지분율만이 아니라 주주간계약 등으로 관련 활동을 지시할 힘, 변동이익 노출, 힘을 이익에 사용할 능력을 유지하는지가 핵심입니다.",
    criteria: ["실질 의결권", "이사회·주요 의사결정권", "변동이익 노출"],
    counter: "회사의 계획은 공시됐지만 실제 연결 결론은 거래일 계약과 사실관계에 따라 재판정해야 합니다.",
    followUps: ["보호권과 지배권의 차이는?", "잠재적 의결권은 어떻게 봅니까?", "감사인이 반대하면 무엇을 제시합니까?"],
    evidence: "계약상 권리와 회계 결론을 증빙한 경험",
    sourceIds: ["krx-deal-latest"],
  },
  {
    category: "회계",
    difficulty: "기본",
    question: "법률상 인수자와 회계상 취득자가 다를 수 있다는 의미는 무엇입니까?",
    thesis: "법적 형식상 신주를 발행한 회사가 완전모회사여도 회계는 누가 결합기업을 실질적으로 지배하는지 보고 취득자를 정한다는 뜻입니다.",
    criteria: ["거래 후 의결권", "이사회·경영진 구성", "상대적 규모·대가 조건"],
    counter: "역취득 가능성을 말하는 것이지, 공개자료만으로 이번 거래의 취득자를 단정하는 것은 아닙니다.",
    followUps: ["취득자가 바뀌면 PPA는 어떻게 달라집니까?", "상대적 규모만으로 결정합니까?", "취득일은 언제입니까?"],
    evidence: "법률·회계·세무 결론을 분리해 문서화한 경험",
    sourceIds: ["krx-deal-original"],
  },
  {
    category: "회계",
    difficulty: "임원",
    question: "PPA에서 세무팀이 담당해야 할 역할은 무엇입니까?",
    thesis: "식별자산별 세무기초가액과 공정가치 차이를 검증하고 이연법인세, 미래 공제, 거래세, 신고와 손상 시 세효과까지 연결해야 합니다.",
    criteria: ["자산별 tax basis", "적용세율·회수방식", "이연세금 검증"],
    counter: "가치평가는 평가팀 역할이지만 세무 가정이 영업권과 미래 손익을 바꾸므로 초기에 참여해야 합니다.",
    followUps: ["고객관계의 세무기초가액이 0이면?", "영업권 세무공제가 가능하면?", "측정기간 조정은 어떻게 관리합니까?"],
    evidence: "M&A·SPC에서 PPA 자료와 세무조정을 연결한 경험",
    sourceIds: ["krx-deal-original"],
  },
  {
    category: "회계",
    difficulty: "CFO 압박",
    question: "영업권이 커지면 어떤 문제가 발생합니까?",
    thesis: "현금유출이 즉시 생기는 것은 아니지만 미래 초과수익 가정 의존도가 커지고, 손상 시 대규모 손익 변동과 투자 판단 실패 신호가 될 수 있습니다.",
    criteria: ["영업권/투하자본", "손상 여유 headroom", "거래량·할인율 민감도"],
    counter: "영업권이 크다는 사실만으로 나쁜 거래는 아니며 식별 불가능한 시너지의 실현 여부가 핵심입니다.",
    followUps: ["손상은 현금흐름에 영향이 없는데 왜 중요합니까?", "어떤 조기경보를 두겠습니까?", "세무상 영업권과 차이는?"],
    evidence: "손익과 현금을 분리해 경영진에게 보고한 경험",
    sourceIds: ["krx-deal-original"],
  },
  {
    category: "세무",
    difficulty: "CFO 압박",
    question: "두나무 거래의 가장 큰 세무 리스크는 무엇입니까?",
    thesis: "단일 세목보다 과세이연 전제와 사후관리의 실패가 주주·회사 현금세금과 거래가치를 동시에 흔드는 것이 가장 큰 리스크입니다.",
    criteria: ["적격요건·사후관리", "주주 유형별 과세", "최악 현금세액·책임주체"],
    counter: "구체적 결론은 계약, 주주 구성, 적용 법령과 유권해석을 확인한 뒤 내려야 합니다.",
    followUps: ["누가 세금을 부담합니까?", "조건부 의견이라면 거래를 중단합니까?", "세무보상 조항은 어떻게 설계합니까?"],
    evidence: "거래 세무의 요건·증빙·현금효과를 체크리스트로 통제한 경험",
    sourceIds: ["krx-deal-original"],
  },
  {
    category: "세무",
    difficulty: "임원",
    question: "적격 주식교환 요건을 충족하지 못하면 어떤 영향이 있습니까?",
    thesis: "과세이연이 부인되면 주주 단계의 즉시 과세, 취득가액 변화, 거래 이탈과 매수청구, 계약상 보상 문제가 연쇄적으로 발생할 수 있습니다.",
    criteria: ["즉시 현금세액", "주주별 부담·원천징수", "거래 종결 선행조건"],
    counter: "영향은 주주 유형과 거래조건마다 달라 세액과 법적 책임을 시나리오별로 산정해야 합니다.",
    followUps: ["회사가 부담할 세금이 아닌데 왜 CFO 이슈입니까?", "보수적 충당이 필요합니까?", "대안 구조는 무엇입니까?"],
    evidence: "세무결론을 거래조건과 이해관계자 행동에 연결한 경험",
    sourceIds: ["krx-deal-original"],
  },
  {
    category: "Pillar 2",
    difficulty: "임원",
    question: "두나무 거래가 Pillar 2에 미치는 영향을 어떻게 분석하겠습니까?",
    thesis: "취득 후 구성기업 범위와 국가별 데이터를 다시 매핑하고 PPA·이연세금·세액공제가 국가별 ETR과 추가세액에 미치는 영향을 거래 전후로 비교하겠습니다.",
    criteria: ["국가별 ETR", "QDMTT·IIR 순서", "PPA·세액공제 조정"],
    counter: "연결 편입만으로 추가세액이 생긴다고 단정할 수 없고 관할국별 구성과 세이프하버를 봐야 합니다.",
    followUps: ["거래연도 데이터가 불완전하면?", "가상자산 평가손익은 어떻게 다룹니까?", "100일 내 무엇을 통합합니까?"],
    evidence: "직접 수행하지 않은 제도도 데이터·책임·통제로 구축한 경험",
    sourceIds: ["oecd-pillar2", "oecd-gmt-2026", "krx-deal-original"],
  },
  {
    category: "세무",
    difficulty: "임원",
    question: "가상자산 사업의 세무 리스크를 어떻게 관리하겠습니까?",
    thesis: "상품·거래흐름·지갑·법인·국가별로 세금 이벤트를 맵핑하고 법인세, 부가세, 원천세, 이전가격, CARF성 보고와 증빙을 시스템 통제로 묶겠습니다.",
    criteria: ["거래유형별 tax event", "지갑-원장-신고 대사", "고위험 예외율"],
    counter: "규정 모니터링만으로는 부족하고 신규 상품 출시 게이트에 세무 승인을 넣어야 합니다.",
    followUps: ["스테이킹 보상은 언제 인식합니까?", "해외 사용자의 PE 위험은?", "시세 데이터는 어떤 통제를 둡니까?"],
    evidence: "ERP·프로세스에 세무 통제를 내재화한 경험",
    sourceIds: ["naver-deal-vision", "oecd-gmt-2026"],
  },
  {
    category: "두나무 거래",
    difficulty: "CFO 압박",
    question: "규제 승인이 계속 지연되면 CFO에게 무엇을 보고하겠습니까?",
    thesis: "지연 사유보다 종결확률·최장 일정·월별 현금소요·가치 훼손·중단 및 재협상 기준을 세 시나리오로 보고하겠습니다.",
    criteria: ["승인 확률·critical path", "월별 burn·기회비용", "walk-away threshold"],
    counter: "일정 연장은 안정적 종결을 위한 선택일 수 있지만 옵션 유지 비용을 매월 재평가해야 합니다.",
    followUps: ["지금 철회하라는 말입니까?", "확률은 어떻게 정합니까?", "조직 사기는 어떻게 관리합니까?"],
    evidence: "불확실한 세무조사·거래에서 시나리오와 보고주기를 운영한 경험",
    sourceIds: ["krx-deal-latest"],
  },
  {
    category: "두나무 거래",
    difficulty: "임원",
    question: "AI와 Web3 시너지를 어떤 KPI로 검증하겠습니까?",
    thesis: "홍보지표가 아니라 교차전환 코호트, CAC, 순수수료, 규제·통합비용을 거친 세후 시너지와 희석 반영 주당가치로 검증하겠습니다.",
    criteria: ["90일 교차전환·유지율", "증분 공헌이익/CAC", "세후 ROIC"],
    counter: "가입자 수 증가는 출발점일 뿐 기존 고객 이동과 인센티브 비용을 제거한 증분값이어야 합니다.",
    followUps: ["첫 6개월 선행지표는?", "시너지 오너는 누구입니까?", "KPI 미달 시 무엇을 중단합니까?"],
    evidence: "세무 절감액을 실제 현금·프로세스 KPI로 전환한 경험",
    sourceIds: ["naver-deal-vision"],
  },
  {
    category: "세무",
    difficulty: "CFO 압박",
    question: "절세와 세무 리스크 중 무엇이 더 중요합니까?",
    thesis: "양자택일이 아니라 위험조정 세후가치가 기준이며, 법적 지속가능성·현금효과·평판을 통과한 절세만 실행하겠습니다.",
    criteria: ["승소·유지 가능성", "세후 NPV", "평판·운영 복잡성"],
    counter: "과도한 보수성도 주주가치를 훼손하므로 명확한 risk appetite 안에서 합법적 인센티브는 적극 활용해야 합니다.",
    followUps: ["공격적 절세의 경계는?", "CFO가 더 하라고 하면?", "이사회에는 어떻게 수치화합니까?"],
    evidence: "세무조사 노출과 환급기회를 한 의사결정표에서 비교한 경험",
  },
  {
    category: "세무",
    difficulty: "기본",
    question: "실효세율과 현금세금의 차이를 CFO에게 설명해 보십시오.",
    thesis: "실효세율은 회계이익 대비 세금비용이고 현금세금은 실제 납부액과 시점이므로 이연세금·전기조정·선납·환급 때문에 다릅니다.",
    criteria: ["ETR bridge", "cash-tax bridge", "3·12개월 납부 전망"],
    counter: "장기적으로 수렴할 수 있지만 투자·결손금·M&A가 있으면 차이가 오래 지속될 수 있습니다.",
    followUps: ["ETR은 낮은데 현금세금이 늘 수 있습니까?", "FCF에는 무엇을 씁니까?", "환급은 언제 반영합니까?"],
    evidence: "세무조정 수치를 현금 납부 캘린더로 바꾼 경험",
  },
  {
    category: "경력 연결",
    difficulty: "기본",
    question: "회계법인과 인하우스 세무팀의 차이는 무엇입니까?",
    thesis: "회계법인이 전문적 쟁점과 독립적 시각을 제공한다면 인하우스는 사업 맥락에서 의사결정을 내리고 실행·데이터·사후통제까지 끝까지 소유합니다.",
    criteria: ["의사결정 속도", "실행 책임", "누적 데이터·통제"],
    counter: "인하우스도 외부 전문성을 배척하지 않고 질문을 정확히 정의하고 품질을 통제해야 합니다.",
    followUps: ["자문 의견과 사업 요구가 충돌하면?", "왜 지금 인하우스입니까?", "외부자문비를 어떻게 관리합니까?"],
    evidence: "자문 결과를 프로세스와 시스템 통제로 정착시킨 경험",
  },
  {
    category: "Pillar 2",
    difficulty: "임원",
    question: "직접 수행하지 않은 Pillar 2 업무를 어떻게 구축하겠습니까?",
    thesis: "아는 척하지 않고 90일 안에 범위·데이터·책임·캘린더·검토 통제를 세우고 전문가 검증을 받아 반복 가능한 프로세스로 만들겠습니다.",
    criteria: ["대상법인 100% 맵핑", "데이터 gap·오너", "드라이런·검토 흔적"],
    counter: "외부자문에 맡기는 것은 시작일 뿐 최종 데이터와 신고 책임은 내부에 남습니다.",
    followUps: ["첫 2주에 무엇을 합니까?", "오류를 어떻게 찾습니까?", "경험 부족이 리스크 아닌가요?"],
    evidence: "새 제도를 체크리스트·ERP·책임자로 내재화한 유사 경험",
    sourceIds: ["oecd-pillar2", "oecd-gmt-2026"],
  },
  {
    category: "지원동기",
    difficulty: "임원",
    question: "입사 후 90일 동안 무엇을 하겠습니까?",
    thesis: "30일 진단, 60일 우선순위 합의, 90일 첫 성과의 3단계로 현금세금 전망·두나무 통합 세무·Pillar 2 데이터 통제 중 가장 큰 gap을 닫겠습니다.",
    criteria: ["30일 이해관계자·데이터맵", "60일 risk/value backlog", "90일 1개 가시적 개선"],
    counter: "모든 것을 바꾸기보다 기존 팀의 강점을 확인하고 CFO가 체감할 한 가지 결과를 먼저 만들겠습니다.",
    followUps: ["첫 성과를 하나만 고르면?", "팀이 반대하면?", "90일 뒤 무엇을 보고합니까?"],
    evidence: "새 조직에서 빠르게 현황을 구조화하고 개선을 정착시킨 경험",
  },
  {
    category: "AI 투자",
    difficulty: "CFO 압박",
    question: "GPU 4,000장은 많습니까, 적습니까?",
    thesis: "수량만으로 판단할 수 없고 학습·추론 수요, 활용률, 처리량, 개발주기 단축, 외부조달 대비 단위원가로 적정성을 판단해야 합니다.",
    criteria: ["가동률·대기시간", "토큰/학습당 총원가", "매출·원가절감 귀속"],
    counter: "선제 확보는 공급 부족의 옵션 가치가 있지만 기술 노후화 비용과 균형해야 합니다.",
    followUps: ["가동률 목표는?", "유휴 GPU는 어떻게 합니까?", "12배 개발속도는 ROI입니까?"],
    evidence: "투자 규모보다 이용률과 현금회수로 성과를 검증한 경험",
    sourceIds: ["naver-ai-cluster"],
  },
  {
    category: "AI 투자",
    difficulty: "임원",
    question: "AI 인프라 투자세액공제를 검토할 때 가장 먼저 볼 것은 무엇입니까?",
    thesis: "자산 명칭이 아니라 실제 기능, 설치·사용 장소, 취득시기, 사업용 사용, 비용 구분과 적용 법령의 대상·제외 요건을 먼저 봅니다.",
    criteria: ["eligible asset population", "가동·취득 시점", "증빙 완결성"],
    counter: "공제율보다 대상 자산의 데이터 품질과 사후관리 실패가 실제 환급을 좌우할 수 있습니다.",
    followUps: ["서버와 네트워크를 어떻게 구분합니까?", "리스자산은?", "공제 후 Pillar 2 영향은?"],
    evidence: "대규모 자산명세를 세법요건과 대사해 잠재환급을 검증한 경험",
    sourceIds: ["naver-ai-cluster", "oecd-pillar2"],
  },
  {
    category: "AI 투자",
    difficulty: "임원",
    question: "AI 데이터센터를 해외에 두면 어떤 세무 이슈가 생깁니까?",
    thesis: "법인·서버·인력·계약의 위치별로 PE, 이전가격, 원천세, VAT/GST, 관세·지방세, 공제와 Pillar 2를 세후 입지모델로 비교합니다.",
    criteria: ["세후 TCO", "PE·nexus", "현금세금·환급 지연"],
    counter: "낮은 명목세율보다 전력·규제·데이터 주권과 실제 운영 실질이 우선입니다.",
    followUps: ["서버만으로 PE가 생깁니까?", "비용분담을 쓰겠습니까?", "어느 법인이 GPU를 소유합니까?"],
    evidence: "해외 종속법인 이전가격과 고정사업장 사실관계를 맵핑한 경험",
    sourceIds: ["naver-ai-factory", "oecd-pillar2"],
  },
  {
    category: "AI 투자",
    difficulty: "CFO 압박",
    question: "AI 투자 수익이 불확실한데 CAPEX를 줄여야 하지 않습니까?",
    thesis: "일괄 삭감보다 수요가 검증된 단계별 게이트, 임대·파트너십 옵션, 활용률과 단위경제성 기준으로 가역성을 높이겠습니다.",
    criteria: ["단계별 NPV", "활용률 하한", "중단·전환 옵션"],
    counter: "너무 늦은 투자는 공급·학습곡선·시장진입 기회를 잃는 비용이 있습니다.",
    followUps: ["중단 기준 숫자를 말해보세요.", "매몰비용은 어떻게 다룹니까?", "Brookfield 구조의 장점은?"],
    evidence: "불확실한 투자안을 시나리오와 단계 승인으로 관리한 경험",
    sourceIds: ["naver-ai-factory", "naver-q1-2026"],
  },
  {
    category: "두나무 거래",
    difficulty: "기본",
    question: "포괄적 주식교환과 합병의 차이를 설명해 보십시오.",
    thesis: "주식교환은 두 회사의 법인격을 유지한 채 한 회사가 다른 회사를 100% 자회사로 만들고, 합병은 한 법인이 다른 법인의 권리·의무를 승계해 법인격이 소멸할 수 있습니다.",
    criteria: ["법인격 존속", "대가·신주", "승인·채권자·세무 절차"],
    counter: "일상적으로 ‘합병’이라 부를 수 있어도 면접에서는 법적 형식을 정확히 표현해야 합니다.",
    followUps: ["왜 주식교환을 택했을까요?", "후속 합병 가능성은?", "세무 차이는?"],
    evidence: "거래 구조별 법률·회계·세무 차이를 설명한 경험",
    sourceIds: ["krx-deal-original"],
  },
  {
    category: "두나무 거래",
    difficulty: "임원",
    question: "주식매수청구권이 왜 CFO의 현금 리스크입니까?",
    thesis: "주식대가 거래라도 반대주주의 청구 규모에 따라 현금 유출과 종결 선행조건 불충족이 동시에 발생할 수 있기 때문입니다.",
    criteria: ["청구 접수액", "1.2조원 해제 기준", "대체 유동성"],
    counter: "최대액이 그대로 지급된다고 단정하지 말고 주주 행동과 계약 조건을 시나리오화해야 합니다.",
    followUps: ["1.2조원 직전이면 종결합니까?", "자금은 어떻게 조달합니까?", "가격 분쟁은 어떻게 반영합니까?"],
    evidence: "세금·거래대금 외 숨은 현금조건을 식별한 경험",
    sourceIds: ["krx-deal-latest"],
  },
  {
    category: "두나무 거래",
    difficulty: "CFO 압박",
    question: "두나무 거래를 한 문장으로 권고한다면?",
    thesis: "전략적 옵션은 크지만 거래량·규제·희석을 보수적으로 반영한 세후 주당가치가 플러스이고 통합·승인 게이트를 지킬 때만 종결을 권고합니다.",
    criteria: ["downside 주당가치", "승인·통합 게이트", "세후 ROIC"],
    counter: "공개자료만으로 찬반을 확정하지 않고 이사회가 볼 내부 실사 숫자를 전제로 한 조건부 권고입니다.",
    followUps: ["결국 찬성입니까 반대입니까?", "가장 큰 downside는?", "당신이라면 어떤 조건을 추가합니까?"],
    evidence: "리스크 나열을 조건부 권고안으로 바꾼 경험",
    sourceIds: ["krx-deal-latest", "naver-deal-vision"],
  },
  {
    category: "회계",
    difficulty: "임원",
    question: "PPA와 이연법인세는 어떻게 연결됩니까?",
    thesis: "PPA로 인식한 자산·부채의 회계상 공정가치와 세무기초가액 차이가 일시적 차이를 만들고, 이연법인세 인식은 순식별자산과 영업권을 다시 바꿉니다.",
    criteria: ["자산별 book-tax basis", "적용세율·회수방식", "영업권 조정"],
    counter: "모든 차이에 동일하게 이연세금을 인식하는 것이 아니라 예외와 회수 가능성을 확인해야 합니다.",
    followUps: ["세율은 어느 국가 것을 씁니까?", "브랜드 가치에는?", "측정기간 중 수정되면?"],
    evidence: "회계 PPA 파일과 세무기초가액 대사를 운영한 경험",
  },
  {
    category: "회계",
    difficulty: "CFO 압박",
    question: "가상자산 고객자산은 NAVER 연결재무제표에 어떻게 보일까요?",
    thesis: "보관 약정, 통제와 경제적 효익, 반환 의무, 본인·대리인 판단을 봐야 하며 공개자료만으로 자산·부채 인식 또는 상계 결론을 단정할 수 없습니다.",
    criteria: ["계약상 권리·의무", "wallet control", "고객 손실 부담"],
    counter: "표시 결론과 별개로 수량·평가·보안·유동성 공시와 내부통제가 중요합니다.",
    followUps: ["해킹 손실은 누구의 부채입니까?", "상계할 수 있습니까?", "감사증거는 어떻게 확보합니까?"],
    evidence: "새로운 거래의 계약·시스템·회계 증거를 연결한 경험",
  },
  {
    category: "세무",
    difficulty: "임원",
    question: "이전가격 정책이 AI와 Web3 통합에 왜 중요합니까?",
    thesis: "데이터·모델·브랜드·고객접점·규제기능의 기여와 위험을 누가 소유하는지 정해야 국가별 이익배분과 현금세금이 지속가능해집니다.",
    criteria: ["DEMPE·기능위험", "계약-실제행동 일치", "정책-실적 모니터링"],
    counter: "벤치마크 마진만 정하는 접근은 무형자산과 플랫폼 네트워크 기여를 놓칩니다.",
    followUps: ["데이터 가치를 어떻게 보상합니까?", "적자가 나면 누가 부담합니까?", "사후조정을 허용합니까?"],
    evidence: "해외 종속법인 기능위험 분석과 정책 운영 경험",
  },
  {
    category: "세무",
    difficulty: "CFO 압박",
    question: "투자세액공제로 실효세율을 낮추면 무조건 좋은 것 아닙니까?",
    thesis: "회계상 ETR 개선, 실제 현금 회수, Pillar 2 추가세액, 사후관리 비용을 함께 봐야 하며 명목 공제액이 순가치와 같지 않습니다.",
    criteria: ["현금 회수기간", "GloBE ETR 영향", "불확실성·사후관리"],
    counter: "그럼에도 적격 투자의 공제는 자본비용을 낮추므로 구조를 왜곡하지 않는 범위에서 적극 확보해야 합니다.",
    followUps: ["환급가능 공제와 비환급 공제 차이는?", "ETR이 15% 아래면?", "공제액을 KPI로 쓰겠습니까?"],
    evidence: "공제 기대액과 실제 환급·세무조사 리스크를 함께 관리한 경험",
    sourceIds: ["oecd-pillar2"],
  },
  {
    category: "Pillar 2",
    difficulty: "기본",
    question: "Pillar 2의 15%는 무엇에 적용됩니까?",
    thesis: "법정세율이 아니라 적용대상 다국적기업의 관할국별 GloBE 소득과 조정대상조세로 계산한 실효세율에 적용되는 최저세율입니다.",
    criteria: ["관할국별 계산", "GloBE income", "covered taxes"],
    counter: "한국 법인세율이 15%보다 높다는 이유만으로 추가세액이 없다고 단정할 수 없습니다.",
    followUps: ["연결 ETR과 차이는?", "손실 국가는?", "세이프하버는 무엇입니까?"],
    evidence: "복잡한 세법 개념을 CFO 언어로 간결하게 설명한 경험",
    sourceIds: ["oecd-pillar2"],
  },
  {
    category: "Pillar 2",
    difficulty: "임원",
    question: "Pillar 2 데이터 품질을 어떻게 통제하겠습니까?",
    thesis: "재무연결 원천과 GloBE 조정 항목의 lineage, 법인별 오너, 자동 검증, 예외 승인과 재수행 가능한 증빙을 통제 프레임으로 만들겠습니다.",
    criteria: ["완전성 대사", "예외 건수·해결일", "review sign-off"],
    counter: "스프레드시트 자체가 문제라기보다 출처·변경·승인 흔적이 없는 것이 문제입니다.",
    followUps: ["ERP 개발 전 임시통제는?", "누가 최종 책임집니까?", "오류 허용 수준은?"],
    evidence: "ERP 연계와 수기조정 통제를 설계한 경험",
    sourceIds: ["oecd-gmt-2026"],
  },
  {
    category: "경력 연결",
    difficulty: "임원",
    question: "세무조사 대응 경험이 CFO 의사결정에 어떤 가치를 줍니까?",
    thesis: "쟁점 방어를 넘어 잠재 현금유출의 범위·확률·시기, 사업 관행의 원인, 재발 통제를 한 장에 제시할 수 있다는 가치가 있습니다.",
    criteria: ["best/base/worst 금액", "납부·불복 일정", "재발 오류율"],
    counter: "추징액 최소화만 강조하면 과도한 방어로 보일 수 있어 사업 지속성과 통제 개선을 함께 말해야 합니다.",
    followUps: ["가장 어려운 이해관계자는?", "패배한 사례는?", "CFO에게 언제 보고합니까?"],
    evidence: "익명화한 조사 쟁점에서 정량 결과와 재발 통제를 연결",
  },
  {
    category: "경력 연결",
    difficulty: "CFO 압박",
    question: "약 281억 원 환급은 회사가 원래 받을 돈인데, 본인의 성과라고 할 수 있습니까?",
    thesis: "권리는 회사에 있었지만 대상 데이터의 범위 정의, 적격성 검증, 부서 조율, 증빙·신고·사후통제를 통해 불확실한 권리를 약 281억 원의 회수 가능한 현금으로 전환한 과정에서 제 직접 기여를 구분해 설명하겠습니다.",
    criteria: ["약 281억 원의 청구·환급 구분", "회수 기간", "오류·부인율"],
    counter: "성과를 과장하지 않고 제 직접 역할과 팀·외부전문가 기여를 구분하겠습니다.",
    followUps: ["본인이 없었어도 됐던 것 아닌가요?", "실제 환급액과 경정청구액은 같습니까?", "환급 기회를 반복적으로 찾는 통제는 무엇입니까?"],
    evidence: "약 281억 원 경정청구·환급 사례에서 기회 발견, 적격성 검증, 증빙과 직접 역할을 구분해 준비",
  },
  {
    category: "경력 연결",
    difficulty: "임원",
    question: "이전가격 경험을 NAVER 글로벌 사업에 어떻게 적용하겠습니까?",
    thesis: "정책 문서가 아니라 서비스 흐름과 데이터·IP·인력의 실제 기여를 계약·가격·청구·세금·Pillar 2 결과까지 일치시키는 운영체계를 만들겠습니다.",
    criteria: ["실제행동 일치", "정책 대비 마진", "분쟁·현금세금"],
    counter: "NAVER의 구체 정책은 입사 후 확인해야 하므로 방법론과 우선 질문 중심의 제안입니다.",
    followUps: ["가장 먼저 볼 거래는?", "로컬팀이 반대하면?", "APA를 추진합니까?"],
    evidence: "해외 법인 정책과 실제 손익 차이를 조정한 익명화 사례",
  },
  {
    category: "경력 연결",
    difficulty: "기본",
    question: "ERP 프로세스 개선이 세무 전문성과 무슨 관계입니까?",
    thesis: "세무 결론이 반복 가능하려면 거래 발생 시점에 올바른 코드·증빙·책임자가 있어야 하므로 ERP 통제는 세무 품질과 결산 속도의 기반입니다.",
    criteria: ["수기조정 건수", "마감일 단축", "오류·예외율"],
    counter: "시스템 개발 자체보다 세법 요구를 데이터 규칙과 업무 책임으로 번역하는 것이 세무팀 역할입니다.",
    followUps: ["자동화 실패 사례는?", "통제와 속도가 충돌하면?", "AI를 어디에 쓰겠습니까?"],
    evidence: "ERP 연계로 수기작업·오류·마감시간을 줄인 경험",
  },
  {
    category: "지원동기",
    difficulty: "CFO 압박",
    question: "왜 NAVER이고, 왜 지금입니까?",
    thesis: "AI 인프라·핀테크·Web3·글로벌 사업이 동시에 재편되는 지금 세무가 사후 신고를 넘어 투자와 거래의 세후 현금흐름을 설계할 수 있는 드문 환경이기 때문입니다.",
    criteria: ["직무 적합성", "현재 사업 과제", "구체 기여 1~2개"],
    counter: "회사 이름이나 성장성보다 제 경험이 어떤 의사결정에 바로 쓰이는지로 지원동기를 증명하겠습니다.",
    followUps: ["다른 플랫폼 회사도 같지 않습니까?", "NAVER의 약점은?", "3년 뒤 무엇을 만들고 싶습니까?"],
    evidence: "세무조정·M&A·공제·ERP 경험을 AI 투자·두나무 통합에 연결",
    sourceIds: ["naver-ai-factory", "krx-deal-latest"],
  },
  {
    category: "지원동기",
    difficulty: "임원",
    question: "당신을 뽑아야 하는 이유를 30초 안에 말해보세요.",
    thesis: "저는 복잡한 세법을 검토하는 데서 멈추지 않고 현금효과·의사결정·통제로 바꿔온 사람이며, 그 역량을 NAVER의 AI 투자와 글로벌 거래에 즉시 연결할 수 있습니다.",
    criteria: ["차별점 1개", "증거 숫자 1개", "NAVER 적용 1개"],
    counter: "일반적인 성실함 대신 익명화 가능한 실제 수치와 직접 역할로 신뢰를 만들겠습니다.",
    followUps: ["숫자로 증명하세요.", "약점은 무엇입니까?", "비슷한 후보와 차이는?"],
    evidence: "가장 강한 정량 STAR 사례 한 개",
  },
  {
    category: "CFO 관점",
    difficulty: "CFO 압박",
    question: "세무팀의 KPI를 절감세액으로 잡겠습니까?",
    thesis: "절감세액만 쓰지 않고 예측 정확도, 현금 회수, 리스크조정 순가치, 결산 속도, 통제 품질을 균형 있게 두겠습니다.",
    criteria: ["cash-tax forecast 오차", "risk-adjusted NPV", "마감·오류율"],
    counter: "절감세액도 중요한 결과 지표지만 과도한 위험추구와 시점 왜곡을 막는 보완지표가 필요합니다.",
    followUps: ["KPI 세 개만 고르면?", "리스크를 어떻게 숫자로 만듭니까?", "사업부와 공동 KPI는?"],
    evidence: "세무팀 성과를 현금·기간·품질 지표로 보고한 경험",
  },
  {
    category: "CFO 관점",
    difficulty: "임원",
    question: "CFO에게 나쁜 소식을 어떻게 보고합니까?",
    thesis: "사실과 추정을 구분해 결론부터 말하고 금액·확률·시기, 즉시 통제, 선택지와 권고, 다음 업데이트 시점을 한 장으로 보고합니다.",
    criteria: ["노출액 범위", "의사결정 마감", "owner·next update"],
    counter: "정확해질 때까지 기다리는 것이 아니라 불확실성 수준을 표시해 조기 경보합니다.",
    followUps: ["본인 실수라면?", "수치가 계속 바뀌면?", "CFO가 화를 내면?"],
    evidence: "세무조사·결산 이슈를 조기 에스컬레이션한 경험",
  },
  {
    category: "CFO 관점",
    difficulty: "CFO 압박",
    question: "세무팀이 사업 속도를 늦춘다는 불만에는 어떻게 답하겠습니까?",
    thesis: "모든 거래를 막는 대신 위험등급별 SLA, 사전 표준안, 고위험 예외의 빠른 의사결정 게이트로 속도와 통제를 함께 높이겠습니다.",
    criteria: ["검토 TAT", "표준안 적용률", "사후 오류·추징"],
    counter: "긴급성을 이유로 중대한 법적·평판 위험을 무시하지 않고 누가 어떤 위험을 승인하는지 명확히 합니다.",
    followUps: ["당일 출시 요청이면?", "누가 risk acceptance 합니까?", "표준안이 낡으면?"],
    evidence: "계열사 거래 매뉴얼로 검토시간과 오류를 줄인 경험",
  },
  {
    category: "세무",
    difficulty: "임원",
    question: "두나무 인수 후 첫 세무 통합 과제는 무엇입니까?",
    thesis: "거래 종결일 기준 tax basis·미결 세무위험·신고 캘린더·데이터 오너를 확정하고 PPA·연결·Pillar 2로 이어지는 day-1 통제부터 세우겠습니다.",
    criteria: ["tax DD issue register", "day-1 ownership", "100일 통합 backlog"],
    counter: "세율 최적화보다 신고 누락과 증빙 단절을 막는 운영 안정화가 먼저입니다.",
    followUps: ["가장 먼저 통합할 시스템은?", "두나무 팀과 충돌하면?", "과거 세무위험은 누가 부담합니까?"],
    evidence: "M&A·SPC 또는 신규법인 세무 운영을 안정화한 경험",
    sourceIds: ["krx-deal-latest"],
  },
  {
    category: "세무",
    difficulty: "CFO 압박",
    question: "세무조사에서 질 가능성이 40%인 1,000억 원 쟁점이라면 어떻게 권고합니까?",
    thesis: "400억 원 기대값만 보지 않고 현금납부 시기, 가산세, 불복비용, 승패 상관관계, 평판과 선례를 반영해 충당·협상·불복 선택지를 권고합니다.",
    criteria: ["best/base/worst 현금", "법적 확률 근거", "선례·평판"],
    counter: "기대값은 출발점일 뿐 비선형 하방과 조직의 risk appetite를 대체하지 못합니다.",
    followUps: ["그래서 싸웁니까 합의합니까?", "40%를 누가 정합니까?", "공시는 어떻게 합니까?"],
    evidence: "조사 쟁점을 확률·금액·일정으로 보고한 익명화 사례",
  },
  {
    category: "CFO 관점",
    difficulty: "임원",
    question: "FCF를 개선하기 위해 세무팀이 할 수 있는 세 가지는?",
    thesis: "현금세금 예측과 납부시기 최적화, 적격 공제·환급의 조기 회수, 거래·이전가격 구조의 지속가능한 세후 개선을 우선하겠습니다.",
    criteria: ["12개월 cash-tax forecast", "환급 cycle time", "반복 세후 절감"],
    counter: "지급 지연만으로 FCF를 꾸미지 않고 법적 지속가능성과 운전자본 관계를 함께 봅니다.",
    followUps: ["첫 달에 가능한 것은?", "세금 납부를 늦추면 좋은가요?", "Pillar 2 이후에도 유효합니까?"],
    evidence: "환급·납부캘린더·세무조정에서 실제 현금효과를 만든 경험",
  },
  {
    category: "CFO 관점",
    difficulty: "CFO 압박",
    question: "주주환원과 AI 투자 중 하나만 선택해야 한다면?",
    thesis: "장기 세후 ROIC가 자본비용을 명확히 넘고 경쟁우위를 만드는 검증된 AI 투자를 우선하되, 단계 게이트와 예측 가능한 최소 환원으로 자본규율을 증명하겠습니다.",
    criteria: ["세후 ROIC", "유동성·신용도", "단계별 검증"],
    counter: "수익경로가 불명확한 투자를 성장이라는 이유로 보호해서는 안 되며 초과현금은 환원해야 합니다.",
    followUps: ["ROIC를 언제까지 기다립니까?", "주가가 저평가라면?", "최소 환원 수준은?"],
    evidence: "여러 세후 투자대안을 우선순위화한 경험",
    sourceIds: ["naver-ai-factory", "naver-q1-2026"],
  },
];

const defaultFramework = [
  "결론을 한 문장으로 먼저 말한다.",
  "숫자·판단기준 두세 개로 근거를 제시한다.",
  "반대 논리와 하방 위험을 인정한다.",
  "권고안, 실행 책임자, 다음 확인 시점을 제시한다.",
];

export const questions: InterviewQuestion[] = seeds.map((seed, index) => ({
  id: `q-${String(index + 1).padStart(2, "0")}`,
  category: seed.category,
  difficulty: seed.difficulty,
  question: seed.question,
  interviewerIntent: `${seed.category} 전문지식을 암기했는지가 아니라, 불확실한 사실을 구분하고 숫자 기준으로 경영진에게 권고할 수 있는지 평가한다.`,
  keyAnswer: [
    seed.thesis,
    `핵심 판단기준은 ${seed.criteria.join(", ")}입니다.`,
    `따라서 사실관계를 확인한 뒤 조건부 권고와 다음 행동까지 제시하겠습니다.`,
  ],
  answerFramework: defaultFramework,
  modelAnswer: `${seed.thesis} 먼저 핵심 기준 세 가지—${seed.criteria.join(", ")}—로 base·downside 시나리오를 만들겠습니다. 각 시나리오에서 손익과 현금, 세무와 사업을 분리해 보겠습니다. ${seed.counter} 최종적으로는 의사결정 기한과 중단 기준을 붙인 조건부 권고안을 CFO에게 보고하겠습니다.`,
  metrics: seed.criteria,
  counterArgument: seed.counter,
  followUps: seed.followUps,
  redFlags: [
    "공개되지 않은 사실이나 세무·회계 결론을 단정한다.",
    "리스크만 나열하고 우선순위·수치·권고안이 없다.",
    "세금비용과 현금세금, 법적 형식과 경제적 실질을 혼동한다.",
  ],
  candidateEvidence: seed.evidence,
  tags: [seed.category, seed.difficulty, ...seed.criteria.slice(0, 2)],
  sourceIds: seed.sourceIds ?? [],
  lastVerifiedAt: LAST_VERIFIED,
}));

export const questionCategories = [...new Set(questions.map((question) => question.category))];

export const getRandomQuestion = (
  pool: InterviewQuestion[],
  previousId?: string,
  random: () => number = Math.random,
) => {
  if (pool.length === 0) return undefined;
  const candidates = pool.length > 1 && previousId ? pool.filter((question) => question.id !== previousId) : pool;
  return candidates[Math.floor(random() * candidates.length)];
};
